# Generated by Django 3.1 on 2021-09-18 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(default='', max_length=50, verbose_name='省份')),
                ('city', models.CharField(default='', max_length=50, verbose_name='城市')),
                ('district', models.CharField(default='', max_length=50, verbose_name='区域')),
                ('address', models.CharField(default='', max_length=100, verbose_name='详细地址')),
                ('contact_name', models.CharField(default='', max_length=20, verbose_name='联系人')),
                ('contact_mobile', models.CharField(default='', max_length=11, verbose_name='联系电话')),
                ('is_default', models.IntegerField(default=0, verbose_name='是否默认配送地址')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'd_address',
                'managed': True,
            },
        ),
    ]
