# Generated by Django 3.1.5 on 2022-08-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_address_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'managed': True, 'verbose_name': '用户配送地址', 'verbose_name_plural': '用户配送地址'},
        ),
    ]
