# Generated by Codex on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.IntegerField(choices=[(0, '买家'), (1, '商家')], default=0, verbose_name='用户角色'),
        ),
    ]
