# Generated by Codex on 2026-06-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='店铺名称')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop/logo/', verbose_name='店铺Logo')),
                ('desc', models.TextField(blank=True, default='', verbose_name='店铺描述')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '关闭')], default=0, verbose_name='店铺状态')),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL, verbose_name='商家')),
            ],
            options={
                'verbose_name': '商家店铺',
                'db_table': 'd_shop',
            },
        ),
    ]
